// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	StartTime string `json:"username"`
	Duration  string `json:"password"`
	Task      string `json:"task"`
}

type Response struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}
