// Code generated by goctl. DO NOT EDIT.
package types

type ExcelMailRequest struct {
	StartTime string `json:"startTime"`
	Duration  string `json:"duration"`
	Task      string `json:"task"`
	Mail      string `json:"mail"`
}

type MessageMailRequest struct {
	StartTime string `json:"startTime"`
	Duration  string `json:"duration"`
	Task      string `json:"task"`
	Mail      string `json:"mail"`
}

type MessageWechatRequest struct {
	StartTime string `json:"startTime"`
	Duration  string `json:"duration"`
	Task      string `json:"task"`
	Mail      string `json:"mail"`
}

type Request struct {
	StartTime string `json:"startTime"`
	Duration  string `json:"duration"`
	Task      string `json:"task"`
}

type Response struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}
