// Code generated by goctl. DO NOT EDIT!
// Source: task.proto

package user

import (
	"context"

	"cron/service/task/rpc/types/task"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Req       = task.Req
	TaskReply = task.TaskReply

	User interface {
		GetUser(ctx context.Context, in *Req, opts ...grpc.CallOption) (*TaskReply, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) GetUser(ctx context.Context, in *Req, opts ...grpc.CallOption) (*TaskReply, error) {
	client := task.NewUserClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}
