// Code generated by goctl. DO NOT EDIT!
// Source: task.proto

package server

import (
	"context"

	"cron/service/task/rpc/internal/logic"
	"cron/service/task/rpc/internal/svc"
	"cron/service/task/rpc/types/task"
)

type TaskServer struct {
	svcCtx *svc.ServiceContext
	task.UnimplementedTaskServer
}

func NewTaskServer(svcCtx *svc.ServiceContext) *TaskServer {
	return &TaskServer{
		svcCtx: svcCtx,
	}
}

func (s *TaskServer) TaskToMonitor(ctx context.Context, in *task.Req) (*task.TaskReply, error) {
	l := logic.NewTaskToMonitorLogic(ctx, s.svcCtx)
	return l.TaskToMonitor(in)
}
