// Code generated by goctl. DO NOT EDIT!
// Source: task.proto

package server

import (
	"context"

	"cron/service/task/rpc/internal/logic"
	"cron/service/task/rpc/internal/svc"
	"cron/service/task/rpc/types/task"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	task.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetUser(ctx context.Context, in *task.Req) (*task.TaskReply, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}
