// Code generated by goctl. DO NOT EDIT!
// Source: task.proto

package taskclient

import (
	"context"

	"cron/service/task/rpc/types/task"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Req       = task.Req
	TaskReply = task.TaskReply

	Task interface {
		TaskToMonitor(ctx context.Context, in *Req, opts ...grpc.CallOption) (*TaskReply, error)
	}

	defaultTask struct {
		cli zrpc.Client
	}
)

func NewTask(cli zrpc.Client) Task {
	return &defaultTask{
		cli: cli,
	}
}

func (m *defaultTask) TaskToMonitor(ctx context.Context, in *Req, opts ...grpc.CallOption) (*TaskReply, error) {
	client := task.NewTaskClient(m.cli.Conn())
	return client.TaskToMonitor(ctx, in, opts...)
}
