// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"cron/service/task/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/excel/mail",
				Handler: taskExcelToEmailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/message/mail",
				Handler: taskMessageToEmailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/message/wechat",
				Handler: taskMessageToWechatHandler(serverCtx),
			},
		},
	)
}
